[package]
name = "darken-assignment1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
ux = "0.1.5"
crossterm = "0.25.0"
tui = "0.19.0"
console = "0.15.2"
num = "0.4.0"
binread = "2.2.0"